apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  initContainers:
    - name: init-busybox
      image: busybox
      command: ["sh", "-c", "echo 'Initializing...'; sleep 20"]
  containers:
    - name: redis-container
      image: redis
