apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  namespace: default  
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: webapp-config-map
              key: APP_COLOR
